-- SellMetrix PostgreSQL Schema
-- Optimized for high-volume write speeds, AI analytics indexing, and object-storage offloading.

-- Enable UUID extension for primary keys
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Organizations
-- Multi-tenant SaaS support.
CREATE TABLE organizations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 2. Agents
-- Salespeople making calls.
CREATE TABLE agents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    name TEXT,
    email TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Index for fast filtering by org:
CREATE INDEX idx_agents_org ON agents(organization_id);

-- 3. Buyers
-- Leads and customers being analyzed across multiple calls.
CREATE TABLE buyers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,

    phone_number TEXT NOT NULL,
    name TEXT,
    email TEXT,

    first_contacted_at TIMESTAMP,
    last_contacted_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT NOW()
);

-- Index for fast lookup when an incoming call arrives
CREATE INDEX idx_buyers_phone ON buyers(phone_number);


-- 4. Calls (Main Table)
-- This is the core table. Heavy transcript data is offloaded to URLs.
CREATE TABLE calls (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),          -- Internal UUID
    telnyx_call_id TEXT UNIQUE NOT NULL,                     -- External Telnyx v3 ID mapping
    
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    agent_id UUID REFERENCES agents(id) ON DELETE SET NULL,
    buyer_id UUID REFERENCES buyers(id) ON DELETE SET NULL,  -- Replaces plaintext buyer_number

    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    duration_seconds INT,

    final_interest_score INT,
    final_intent TEXT,

    transcript_url TEXT,                                     -- MinIO s3://...
    audio_url TEXT,                                          -- MinIO s3://...

    created_at TIMESTAMP DEFAULT NOW()
);

-- Important indexes:
CREATE INDEX idx_calls_org ON calls(organization_id);
CREATE INDEX idx_calls_agent ON calls(agent_id);
CREATE INDEX idx_calls_buyer ON calls(buyer_id);
CREATE INDEX idx_calls_time ON calls(started_at);

-- 5. Call Events (Core Event Stream)
-- Gong-style scalable architecture. Every insight, transcript chunk, and score update is appended here.
CREATE TABLE call_events (
    id BIGSERIAL PRIMARY KEY,
    call_id UUID REFERENCES calls(id) ON DELETE CASCADE,

    event_type TEXT NOT NULL,                                -- e.g. 'transcript', 'intent_detected', 'score_update'
    event_time_seconds INT NOT NULL,                         -- Offset in seconds from call start

    payload JSONB NOT NULL,                                  -- The dynamic structured data for this event type
    created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for high-speed event reconstruction and analytics filtering
CREATE INDEX idx_call_events_call ON call_events(call_id);
CREATE INDEX idx_call_events_type ON call_events(event_type);
-- Using GIN index for JSONB payload queries (e.g., finding specific intents quickly!)
CREATE INDEX idx_call_events_payload ON call_events USING GIN (payload);

-- 6. Call Summaries
-- Generated by the LLM after the call ends (Step 3).
CREATE TABLE call_summaries (
    call_id UUID PRIMARY KEY REFERENCES calls(id) ON DELETE CASCADE,
    
    summary TEXT,
    action_items TEXT,
    sentiment TEXT,
    
    created_at TIMESTAMP DEFAULT NOW()
);
